ecs_cluster_name = "mwaiyee-ecs-cluster-dev"
ecs_service_name = "mwaiyee-ecs-service-dev"
ecs_task_defn_family = "mwaiyee-ecs-task-def-dev"
ecs_container_name = "mwaiyee-container-dev"
ecs_port_name = "mwaiyee-3000-tcp-dev"