ecs_cluster_name = "mwaiyee-ecs-cluster-prod"
ecs_service_name = "mwaiyee-ecs-service-prod"
ecs_task_defn_family = "mwaiyee-ecs-task-def-prod"
ecs_container_name = "mwaiyee-container-prod"
ecs_port_name = "mwaiyee-3000-tcp-prod"