ecs_cluster_name = "mwaiyee-ecs-cluster-uat"
ecs_service_name = "mwaiyee-ecs-service-uat"
ecs_task_defn_family = "mwaiyee-ecs-task-def-uat"
ecs_container_name = "mwaiyee-container-uat"
ecs_port_name = "mwaiyee-3000-tcp-uat"